<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class PictureRepository extends EntityRepository
{
    public function getManyPictures($start, $take, $latest = false)
    {

        $dql = "SELECT p.id, p.path, p.title, DATE_FORMAT(p.createdAt, '%d %M %Y') as createdAt, u.username, u.id as userID, p.numberOfComments, p.numberOfTags";
        $dql .= " FROM AppBundle:Picture p";
        $dql .= " LEFT JOIN p.createdBy u";
        //if I want the latest pictures
        if ($latest) {
            $dql .= " ORDER BY p.createdAt DESC";
        }

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setFirstResult($start)
            ->setMaxResults($take)
            ->getResult();
    }
}
