<?php

namespace AppBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getManyForSuggest($query)
    {
        $dql = "SELECT t.id, t.name FROM AppBundle:Tag t";
        $dql .= " WHERE t.name LIKE :query";
        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('query', '%' . $query . '%')
            ->getResult();
    }
}
