<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getManyPictures($start, $take, $id)
    {
        $dql = "SELECT p.id, p.path, p.title, DATE_FORMAT(p.createdAt, '%d %M %Y') as createdAt, p.description FROM AppBundle:User u ";
        $dql .= " LEFT JOIN u.pictures p";
        $dql .= " WHERE u.id = :id";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter(':id', $id)
            ->setFirstResult($start)
            ->setMaxResults($take)
            ->getResult();
    }
}
